In [1]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/ACA")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
# source("/mnt/lareaulab/reliscu/code/upper_first.R")

library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [2]:
mod_def <- "PosBC"
unique <- FALSE

## Prep DE genes

### ACA pseudobulk DE genes

In [50]:
set_source <- "yao_2021_ACA_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes"

pairwise_res_list <- readRDS("data/DE_genes/yao_2021_ACA_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")
marker_genes_list <- prep_DE_genes(pairwise_res_list, pairwise=TRUE, unique=unique)

In [52]:
names(marker_genes_list)

 [1] "Endo"        "L2_3_IT_CTX" "L2_3_IT_PPP" "L4_5_IT_CTX" "L5_6_NP_CTX"
 [6] "L5_IT_CTX"   "L5_PT_CTX"   "L6_CT_CTX"   "L6_IT_CTX"   "L6b_CTX"
[11] "Lamp5"       "Oligo"       "Pvalb"       "Sncg"        "Sst_Chodl"
[16] "Vip"

### MOp pseudobulk DE genes

In [3]:
set_source <- "yao_2021_MOp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes"

pairwise_res_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/pseudobulk_test/yao_2021/MOp/data/DE_genes/yao_2021_MOp_STAR_donor_subclass_label_pseudobulk_pairwise_DE_genes_dream.RDS")
marker_genes_list <- prep_DE_genes(pairwise_res_list, pairwise=TRUE, unique=unique)
names(marker_genes_list) <- unlist(sapply(names(marker_genes_list), function(x) gsub(" ", "_", x)))

In [4]:
names(marker_genes_list)

 [1] "Astro"       "Car3"        "L2_3_IT_CTX" "L4_5_IT_CTX" "L5_6_NP_CTX"
 [6] "L5_IT_CTX"   "L5_PT_CTX"   "L6_CT_CTX"   "L6_IT_CTX"   "L6b_CTX"
[11] "Lamp5"       "Pvalb"       "SMC-Peri"    "Sncg"        "Sst_Chodl"
[16] "Vip"

### Claude marker genes

In [10]:
set_source <- "Claude_marker_genes"

marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_mouse.RDS")
names(marker_genes_list) <- sapply(names(marker_genes_list), function(x) gsub(" ", "_", gsub("/", "_", x, fixed=TRUE)))

### Gugene DE genes

In [ ]:
# marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/kang_2026_preprint/kang_2026_preprint_Jorstad_2023_DE_genes.RData")
# marker_genes_list <- lapply(marker_genes_list, convert_genes)

# marker_genes_list1 <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/kang_2026_preprint/kang_2026_preprint_Jorstad_2023_DE_genes.RData")
# marker_genes_list2 <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/kang_2026_preprint/kang_2026_preprint_Gabitto_2024_DE_genes.RData")

# marker_genes_list <- lapply(seq_along(marker_genes_list1), function(i) {
#     union(marker_genes_list1[[i]], marker_genes_list2[[i]])
# })
# marker_genes_list <- lapply(marker_genes_list, convert_genes)

## Round 1 (cell_type, pcntVar = 20, mergeParam = 0.85)

In [4]:
network_dir <- "yao_2021_ACA_STAR_20pcntCells_25SD_200samples_pseudobulk_mergeParam0.85_Modules"
dataset <- "20pcntCells_25SD_200samples_pseudobulk_mergeParam0.85"

In [ ]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [ ]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  endothelial_cell
2  oligodendrocyte
3  pvalb_GABAergic_cortical_interneuron
4  L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
5  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
6  sst_chodl_GABAergic_cortical_interneuron
7  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
8  VIP_GABAergic_cortical_interneuron
9  lamp5_GABAergic_cortical_interneuron
10 sncg_GABAergic_cortical_interneuron
11 L6b_glutamatergic_cortical_neuron
12 L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
13 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
14 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
15 sst_GABAergic_cortical_interneuron
   Pval          Qval          Module
1   0.000000e+00  0.000000e+00 turquoise
2  2.166937e-245 3.533801e-242 blue
3  1.892308e-158 1.567462e-155 brown
4  3.973249e-156 3.239750e-153 purple
5  3.199823e-134 2.140804e-131 magenta
6  6.364315e-109 2.863119e-106 pink
7   2.437433e-96  1.042602e-93 tan
8   1.971001e-89  7.973385e-87 tan
9   2.094271e-85  7.806394e-83 cyan
10  8.289753e-82  2.670375e-79 purple
11  5.443817e-79  1.578253e-76 lightyellow
12  7.404429e-77  1.991753e-74 black
13  1.395554e-42  2.161038e-40 darkgrey
14  2.896621e-38  4.074398e-36 saddlebrown
15  5.013732e-25  6.304617e-23 tan
   Network
1  Bicor-None_signum0.121_minSize10_merge_ME_0.85_19015
2  Bicor-None_signum0.324_minSize8_merge_ME_0.85_19015
3  Bicor-None_signum0.41_minSize10_merge_ME_0.85_19015
4  Bicor-None_signum0.277_minSize8_merge_ME_0.85_19015
5  Bicor-None_signum0.277_minSize10_merge_ME_0.85_19015
6  Bicor-None_signum0.674_minSize12_merge_ME_0.85_19015
7  Bicor-None_signum0.674_minSize10_merge_ME_0.85_19015
8  Bicor-None_signum0.245_minSize15_merge_ME_0.85_19015
9  Bicor-None_signum0.41_minSize12_merge_ME_0.85_19015
10 Bicor-None_signum0.674_minSize12_merge_ME_0.85_19015
11 Bicor-None_signum0.674_minSize6_merge_ME_0.85_19015
12 Bicor-None_signum0.674_minSize12_merge_ME_0.85_19015
13 Bicor-None_signum0.277_minSize12_merge_ME_0.85_19015
14 Bicor-None_signum0.41_minSize8_merge_ME_0.85_19015
15 Bicor-None_signum0.41_minSize12_merge_ME_0.85_19015

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/yao_2021_ACA_pairwise_DE_genes_dream_unique", unique, "_", dataset, "_", mod_def, "_top_Qval_modules.csv"), row.names=FALSE, quote=FALSE)

## Round 2 (cell_type, pcntVar = 20, mergeParam = 0.9)

In [ ]:
network_dir <- "yao_2021_ACA_STAR_20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.9_Modules"
dataset <- "20pcntCells_20pcntVar_200samples_pseudobulk_mergeParam0.9"

In [ ]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [ ]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [ ]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
2  endothelial_cell
3  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
4  oligodendrocyte
5  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
6  pvalb_GABAergic_cortical_interneuron
7  L6b_glutamatergic_cortical_neuron
8  VIP_GABAergic_cortical_interneuron
9  L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
10 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
11 sncg_GABAergic_cortical_interneuron
12 sst_chodl_GABAergic_cortical_interneuron
13 lamp5_GABAergic_cortical_interneuron
14 sst_GABAergic_cortical_interneuron
15 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
   Pval          Qval          Module
1  4.867242e-133 1.984043e-128 blue
2  5.183388e-113 1.039269e-108 black
3   1.372387e-72  2.358545e-69 turquoise
4   6.760142e-68  1.070059e-64 brown
5   3.526575e-67  5.303087e-64 darkmagenta
6   5.709826e-53  3.150881e-50 yellow
7   1.143973e-47  5.135071e-45 skyblue
8   2.335827e-42  8.836479e-40 sienna3
9   3.698239e-39  1.195963e-36 lightgreen
10  1.468323e-22  2.123068e-20 pink
11  1.045791e-19  1.344110e-17 rosybrown2
12  3.088655e-12  2.676982e-10 saddlebrown
13  2.275318e-09  1.683400e-07 lemonchiffon2
14  5.553511e-05  2.599562e-03 paleturquoise1
15  7.276985e-04  2.625739e-02 blue
   Network
1  Bicor-None_signum0.341_minSize12_merge_ME_0.9_19017
2  Bicor-None_signum0.205_minSize15_merge_ME_0.9_19017
3  Bicor-None_signum0.341_minSize15_merge_ME_0.9_19017
4  Bicor-None_signum0.341_minSize12_merge_ME_0.9_19017
5  Bicor-None_signum0.341_minSize8_merge_ME_0.9_19017
6  Bicor-None_signum0.341_minSize12_merge_ME_0.9_19017
7  Bicor-None_signum0.205_minSize12_merge_ME_0.9_19017
8  Bicor-None_signum0.205_minSize12_merge_ME_0.9_19017
9  Bicor-None_signum0.0858_minSize15_merge_ME_0.9_19017
10 Bicor-None_signum0.341_minSize10_merge_ME_0.9_19017
11 Bicor-None_signum0.205_minSize4_merge_ME_0.9_19017
12 Bicor-None_signum0.147_minSize15_merge_ME_0.9_19017
13 Bicor-None_signum0.0858_minSize6_merge_ME_0.9_19017
14 Bicor-None_signum0.0858_minSize8_merge_ME_0.9_19017
15 Bicor-None_signum0.176_minSize12_merge_ME_0.9_19017

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_Qval_modules.csv"), row.names=FALSE, quote=FALSE)

## Round 3 (cell_type, SD = 25, mergeParam = 0.85)

In [114]:
network_dir <- "yao_2021_ACA_STAR_SyntheticDataset1_cell_type_20pcntCells_25SD_200samples_pseudobulk_mergeParam0.85_Modules"

In [115]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [116]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [117]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type
1  endothelial_cell
2  oligodendrocyte
3  pvalb_GABAergic_cortical_interneuron
4  L4_5_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
5  L5_6_near-projecting_glutamatergic_neuron_of_the_primary_motor_cortex
6  sst_chodl_GABAergic_cortical_interneuron
7  L6_corticothalamic-projecting_glutamatergic_cortical_neuron
8  VIP_GABAergic_cortical_interneuron
9  lamp5_GABAergic_cortical_interneuron
10 sncg_GABAergic_cortical_interneuron
11 L6b_glutamatergic_cortical_neuron
12 L6_intratelencephalic_projecting_glutamatergic_neuron_of_the_primary_motor_cortex
13 L2_3-6_intratelencephalic_projecting_glutamatergic_neuron
14 L5_extratelencephalic_projecting_glutamatergic_cortical_neuron
15 sst_GABAergic_cortical_interneuron
   Pval          Qval          Module
1   0.000000e+00  0.000000e+00 turquoise
2  2.166937e-245 3.533801e-242 blue
3  1.892308e-158 1.567462e-155 brown
4  3.973249e-156 3.239750e-153 purple
5  3.199823e-134 2.140804e-131 magenta
6  6.364315e-109 2.863119e-106 pink
7   2.437433e-96  1.042602e-93 tan
8   1.971001e-89  7.973385e-87 tan
9   2.094271e-85  7.806394e-83 cyan
10  8.289753e-82  2.670375e-79 purple
11  5.443817e-79  1.578253e-76 lightyellow
12  7.404429e-77  1.991753e-74 black
13  1.395554e-42  2.161038e-40 darkgrey
14  2.896621e-38  4.074398e-36 saddlebrown
15  5.013732e-25  6.304617e-23 tan
   Network
1  Bicor-None_signum0.121_minSize10_merge_ME_0.85_19015
2  Bicor-None_signum0.324_minSize8_merge_ME_0.85_19015
3  Bicor-None_signum0.41_minSize10_merge_ME_0.85_19015
4  Bicor-None_signum0.277_minSize8_merge_ME_0.85_19015
5  Bicor-None_signum0.277_minSize10_merge_ME_0.85_19015
6  Bicor-None_signum0.674_minSize12_merge_ME_0.85_19015
7  Bicor-None_signum0.674_minSize10_merge_ME_0.85_19015
8  Bicor-None_signum0.245_minSize15_merge_ME_0.85_19015
9  Bicor-None_signum0.41_minSize12_merge_ME_0.85_19015
10 Bicor-None_signum0.674_minSize12_merge_ME_0.85_19015
11 Bicor-None_signum0.674_minSize6_merge_ME_0.85_19015
12 Bicor-None_signum0.674_minSize12_merge_ME_0.85_19015
13 Bicor-None_signum0.277_minSize12_merge_ME_0.85_19015
14 Bicor-None_signum0.41_minSize8_merge_ME_0.85_19015
15 Bicor-None_signum0.41_minSize12_merge_ME_0.85_19015

In [107]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type  Pval         Qval         Module
1  Endo       4.014688e-23 4.441851e-18 turquoise
2  Oligo      3.000326e-08 1.508891e-04 cyan
3  OPC        9.098239e-07 3.728256e-03 brown
4  Micro/PVM  7.925762e-06 2.307648e-02 black
5  Pax6       1.093314e-05 3.024106e-02 darkmagenta
6  VLMC       2.530937e-05 5.490644e-02 black
7  L2/3 IT    2.447831e-05 5.490644e-02 magenta1
8  Astro      7.573647e-05 1.341814e-01 orangered1
9  L4 IT      7.761761e-05 1.341814e-01 plum4
10 Sncg       1.263400e-04 1.777751e-01 darkolivegreen
11 Lamp5      1.329133e-04 1.793357e-01 turquoise2
12 Pvalb      1.763790e-04 1.995916e-01 salmon
13 Sst        6.901720e-04 3.769170e-01 indianred3
14 Sst Chodl  8.421460e-04 4.149240e-01 magenta4
15 Vip        1.086051e-03 4.491183e-01 maroon
16 L6 CT      1.419302e-03 5.341209e-01 lightgreen
17 L6 IT      1.578137e-03 5.609906e-01 gray80
18 L5 ET      2.175973e-03 6.577859e-01 darkorange
19 Chandelier 2.208782e-03 6.630841e-01 lemonchiffon1
20 L6 IT Car3 2.934480e-03 7.518699e-01 plum1
21 L5 IT      3.311603e-03 8.070392e-01 lightpink
22 L5/6 NP    4.500162e-03 9.289141e-01 slateblue3
23 L6b        5.099407e-03 9.915614e-01 white
24 Lamp5 Lhx6 1.000000e+00 1.000000e+00 aliceblue
   Network
1  Bicor-None_signum0.22_minSize6_merge_ME_0.95_26598
2  Bicor-None_signum0.783_minSize3_merge_ME_0.95_26598
3  Bicor-None_signum0.333_minSize6_merge_ME_0.95_26598
4  Bicor-None_signum0.258_minSize10_merge_ME_0.95_26598
5  Bicor-None_signum0.597_minSize6_merge_ME_0.95_26598
6  Bicor-None_signum0.22_minSize6_merge_ME_0.95_26598
7  Bicor-None_signum0.597_minSize4_merge_ME_0.95_26598
8  Bicor-None_signum0.258_minSize8_merge_ME_0.95_26598
9  Bicor-None_signum0.783_minSize3_merge_ME_0.95_26598
10 Bicor-None_signum0.783_minSize3_merge_ME_0.95_26598
11 Bicor-None_signum0.196_minSize8_merge_ME_0.95_26598
12 Bicor-None_signum0.783_minSize8_merge_ME_0.95_26598
13 Bicor-None_signum0.783_minSize3_merge_ME_0.95_26598
14 Bicor-None_signum0.333_minSize6_merge_ME_0.95_26598
15 Bicor-None_signum0.22_minSize6_merge_ME_0.95_26598
16 Bicor-None_signum0.333_minSize6_merge_ME_0.95_26598
17 Bicor-None_signum0.22_minSize6_merge_ME_0.95_26598
18 Bicor-None_signum0.597_minSize4_merge_ME_0.95_26598
19 Bicor-None_signum0.22_minSize6_merge_ME_0.95_26598
20 Bicor-None_signum0.258_minSize6_merge_ME_0.95_26598
21 Bicor-None_signum0.597_minSize3_merge_ME_0.95_26598
22 Bicor-None_signum0.333_minSize8_merge_ME_0.95_26598
23 Bicor-None_signum0.196_minSize8_merge_ME_0.95_26598
24 Bicor-None_signum0.196_minSize10_merge_ME_0.95_26598

In [ ]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_Qval_modules.csv"), row.names=FALSE, quote=FALSE)

## Round 4 (subclass_label, SD = 25, mergeParam = 0.95)

In [11]:
network_dir <- "yao_2021_ACA_STAR_SyntheticDataset1_subclass_label_20pcntCells_25SD_200samples_mergeParam0.95_subsetCutoff8.24_Modules"

In [12]:
enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

In [16]:
# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)

In [17]:
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

   Cell_type  Pval         Qval         Module
1  Oligo      2.014753e-25 5.805007e-21 blue
2  Endo       1.061499e-22 8.738411e-19 turquoise
3  Sncg       1.021633e-18 3.364093e-15 greenyellow
4  Pvalb      1.202202e-15 3.222180e-12 pink
5  Sst        2.629672e-15 6.588470e-12 magenta
6  Micro_PVM  2.356705e-13 5.223275e-10 ghostwhite
7  OPC        1.067019e-12 2.195963e-09 blue
8  L6b        2.967213e-12 5.896056e-09 darkolivegreen
9  L6_IT_Car3 1.340245e-10 2.175539e-07 darkred
10 Peri       4.529085e-08 4.046333e-05 turquoise
11 Astro      1.605141e-04 3.012908e-02 lightyellow
12 VLMC       2.523957e-03 2.673585e-01 darkorange1
   Network
1  Bicor-None_signum0.22_minSize10_merge_ME_0.95_26598
2  Bicor-None_signum0.597_minSize3_merge_ME_0.95_26598
3  Bicor-None_signum0.783_minSize6_merge_ME_0.95_26598
4  Bicor-None_signum0.783_minSize10_merge_ME_0.95_26598
5  Bicor-None_signum0.783_minSize8_merge_ME_0.95_26598
6  Bicor-None_signum0.258_minSize6_merge_ME_0.95_26598
7  Bicor-None_signum0.22_minSize6_merge_ME_0.95_26598
8  Bicor-None_signum0.333_minSize6_merge_ME_0.95_26598
9  Bicor-None_signum0.783_minSize6_merge_ME_0.95_26598
10 Bicor-None_signum0.783_minSize6_merge_ME_0.95_26598
11 Bicor-None_signum0.597_minSize3_merge_ME_0.95_26598
12 Bicor-None_signum0.258_minSize6_merge_ME_0.95_26598

In [18]:
write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)